In [33]:
# https://www.kaggle.com/datasets/uciml/student-alcohol-consumption


import pandas as pd
import numpy as np

df=pd.read_csv("student-mat.csv")
df.head(10)

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0     GP   F   18       U     GT3       A     4     4   at_home   teacher   
1     GP   F   17       U     GT3       T     1     1   at_home     other   
2     GP   F   15       U     LE3       T     1     1   at_home     other   
3     GP   F   15       U     GT3       T     4     2    health  services   
4     GP   F   16       U     GT3       T     3     3     other     other   
5     GP   M   16       U     LE3       T     4     3  services     other   
6     GP   M   16       U     LE3       T     2     2     other     other   
7     GP   F   17       U     GT3       A     4     4     other   teacher   
8     GP   M   15       U     LE3       A     3     2  services     other   
9     GP   M   15       U     GT3       T     3     4     other     other   

   ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0  ...      4        3      4     1     1      3        6   5   6   6  
1  ...      5        3      3     1     1      3        4   5   5   6  
2  ...      4        3      2     2     3      3       10   7   8  10  
3  ...      3        2      2     1     1      5        2  15  14  15  
4  ...      4        3      2     1     2      5        4   6  10  10  
5  ...      5        4      2     1     2      5       10  15  15  15  
6  ...      4        4      4     1     1      3        0  12  12  11  
7  ...      4        1      4     1     1      1        6   6   5   6  
8  ...      4        2      2     1     1      1        0  16  18  19  
9  ...      5        5      1     1     1      5        0  14  15  15  

[10 rows x 33 columns]

# Bedeutung der Spalten

* school - student's school (binary: 'GP' - Gabriel Pereira or 'MS' - Mousinho da Silveira)
* sex - student's sex (binary: 'F' - female or 'M' - male)
* age - student's age (numeric: from 15 to 22)
* address - student's home address type (binary: 'U' - urban or 'R' - rural)
* famsize - family size (binary: 'LE3' - less or equal to 3 or 'GT3' - greater than 3)
* Pstatus - parent's cohabitation status (binary: 'T' - living together or 'A' - apart)
* Medu - mother's education (numeric: 0 - none, 1 - primary education (4th grade), 2 – 5th to 9th grade, 3 – secondary education or 4 – higher education)
* Fedu - father's education (numeric: 0 - none, 1 - primary education (4th grade), 2 – 5th to 9th grade, 3 – secondary education or 4 – higher education)
* Mjob - mother's job (nominal: 'teacher', 'health' care related, civil 'services' (e.g. administrative or police), 'at_home' or 'other')
* Fjob - father's job (nominal: 'teacher', 'health' care related, civil 'services' (e.g. administrative or police), 'at_home' or 'other')
* reason - reason to choose this school (nominal: close to 'home', school 'reputation', 'course' preference or 'other')
* guardian - student's guardian (nominal: 'mother', 'father' or 'other')
* traveltime - home to school travel time (numeric: 1 - <15 min., 2 - 15 to 30 min., 3 - 30 min. to 1 hour, or 4 - >1 hour)
* studytime - weekly study time (numeric: 1 - <2 hours, 2 - 2 to 5 hours, 3 - 5 to 10 hours, or 4 - >10 hours)
* failures - number of past class failures (numeric: n if 1<=n<3, else 4)
* schoolsup - extra educational support (binary: yes or no)
* famsup - family educational support (binary: yes or no)
* paid - extra paid classes within the course subject (Math or Portuguese) (binary: yes or no)
* activities - extra-curricular activities (binary: yes or no)
* nursery - attended nursery school (binary: yes or no)
* higher - wants to take higher education (binary: yes or no)
* internet - Internet access at home (binary: yes or no)
* romantic - with a romantic relationship (binary: yes or no)
* famrel - quality of family relationships (numeric: from 1 - very bad to 5 - excellent)
* freetime - free time after school (numeric: from 1 - very low to 5 - very high)
* goout - going out with friends (numeric: from 1 - very low to 5 - very high)
* Dalc - workday alcohol consumption (numeric: from 1 - very low to 5 - very high)
* Walc - weekend alcohol consumption (numeric: from 1 - very low to 5 - very high)
* health - current health status (numeric: from 1 - very bad to 5 - very good)
* absences - number of school absences (numeric: from 0 to 93)
* These grades are related with the course subject, Math or Portuguese:

* G1 - first period grade (numeric: from 0 to 20)
* G2 - second period grade (numeric: from 0 to 20)
* G3 - final grade (numeric: from 0 to 20, output target)

In [34]:
arr=df.values

In [35]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [36]:
df["Walc"]

0      1
1      1
2      3
3      1
4      2
      ..
390    5
391    4
392    3
393    4
394    3
Name: Walc, Length: 395, dtype: int64

In [37]:
walc_index=27
dalc_index=26
age_index=2
sex_index=1

In [38]:
col_index={}
i=0

for col in df.columns:
    col_index[col]=i
    i+=1

col_index

{'school': 0,
 'sex': 1,
 'age': 2,
 'address': 3,
 'famsize': 4,
 'Pstatus': 5,
 'Medu': 6,
 'Fedu': 7,
 'Mjob': 8,
 'Fjob': 9,
 'reason': 10,
 'guardian': 11,
 'traveltime': 12,
 'studytime': 13,
 'failures': 14,
 'schoolsup': 15,
 'famsup': 16,
 'paid': 17,
 'activities': 18,
 'nursery': 19,
 'higher': 20,
 'internet': 21,
 'romantic': 22,
 'famrel': 23,
 'freetime': 24,
 'goout': 25,
 'Dalc': 26,
 'Walc': 27,
 'health': 28,
 'absences': 29,
 'G1': 30,
 'G2': 31,
 'G3': 32}

# Wochend-Alkoholkonsum der Frauen

In [39]:
# wir selektieren die Spalte mit dem Geschlecht
arr[:, col_index["sex"]]

array(['F', 'F', 'F', 'F', 'F', 'M', 'M', 'F', 'M', 'M', 'F', 'F', 'M',
       'M', 'M', 'F', 'F', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'F', 'F',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'F', 'M', 'M', 'F',
       'F', 'F', 'M', 'M', 'M', 'F', 'F', 'F', 'M', 'M', 'F', 'F', 'F',
       'M', 'F', 'F', 'F', 'F', 'M', 'M', 'F', 'F', 'F', 'F', 'F', 'F',
       'F', 'M', 'F', 'F', 'F', 'M', 'M', 'F', 'M', 'F', 'M', 'M', 'F',
       'M', 'F', 'M', 'M', 'F', 'M', 'F', 'F', 'F', 'F', 'M', 'M', 'F',
       'F', 'F', 'F', 'M', 'F', 'M', 'F', 'F', 'F', 'M', 'M', 'M', 'F',
       'M', 'F', 'F', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'F', 'M', 'M',
       'F', 'F', 'F', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'M', 'F',
       'F', 'M', 'F', 'F', 'F', 'M', 'M', 'M', 'M', 'F', 'M', 'F', 'M',
       'M', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'F', 'F',
       'F', 'M', 'M', 'M', 'F', 'F', 'M', 'F', 'M', 'M', 'M', 'M

In [40]:
# wir machen daraus eine Liste mit True/False
arr[:, sex_index]=='F'

array([ True,  True,  True,  True,  True, False, False,  True, False,
       False,  True,  True, False, False, False,  True,  True,  True,
       False, False, False, False, False, False,  True,  True, False,
       False, False, False, False, False, False, False, False,  True,
       False, False,  True,  True,  True, False, False, False,  True,
        True,  True, False, False,  True,  True,  True, False,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False, False,
        True, False,  True, False, False,  True, False,  True, False,
       False,  True, False,  True,  True,  True,  True, False, False,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True, False, False, False,  True, False,  True,  True, False,
       False,  True, False,  True,  True, False, False, False, False,
       False, False, False,  True, False,  True, False,  True, False,
        True,  True,

In [41]:
# das wird unser woman_index
woman_index=arr[:, sex_index]=='F'

In [42]:
# wir selektieren alle Zeilen bei denen im womand_index True steht und die Spalte walc_index

arr[woman_index, walc_index]

array([1, 1, 3, 1, 2, 1, 2, 1, 2, 2, 1, 1, 3, 1, 1, 1, 2, 2, 1, 4, 1, 3,
       1, 3, 4, 1, 1, 1, 3, 5, 1, 4, 4, 2, 2, 3, 3, 4, 4, 3, 2, 1, 3, 3,
       2, 3, 3, 3, 3, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2,
       2, 3, 4, 1, 1, 1, 1, 3, 2, 1, 1, 3, 1, 5, 1, 1, 1, 1, 1, 4, 3, 3,
       2, 3, 1, 1, 1, 3, 2, 5, 3, 3, 2, 1, 4, 2, 1, 4, 1, 2, 1, 2, 3, 4,
       4, 1, 2, 1, 1, 1, 1, 3, 2, 2, 1, 1, 1, 1, 1, 3, 1, 1, 2, 2, 3, 3,
       1, 1, 3, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 3, 2, 1, 1, 1, 2, 1, 3, 2,
       1, 2, 1, 1, 2, 1, 5, 3, 2, 1, 2, 3, 3, 3, 2, 1, 1, 1, 1, 3, 2, 3,
       1, 3, 3, 2, 2, 3, 3, 1, 2, 2, 1, 4, 3, 1, 2, 2, 2, 2, 1, 1, 3, 1,
       2, 1, 4, 2, 3, 3, 2, 2, 1, 1], dtype=object)

In [43]:
woman_walc=arr[woman_index, walc_index]

In [44]:
men_index=arr[:, sex_index]=='M'
men_walc=arr[men_index, walc_index]

# oder als einzeiler
men_walc=arr[arr[:, sex_index]=='M', walc_index]

In [45]:
woman_walc.mean()

1.9567307692307692

In [46]:
men_walc.mean()

2.663101604278075

# Wer trinkt mehr, Mathe-Kurs oder portugiesisch Kurs?

In [47]:
df_port=pd.read_csv("student-por.csv")
df_mat=pd.read_csv("student-mat.csv")

arr_mat=df_mat.values
arr_port=df_port.values

alc_mat=(arr_mat[:, col_index["Walc"]]+arr_mat[:, col_index["Dalc"]]).mean()
alc_port=(arr_port[:, col_index["Walc"]]+arr_port[:, col_index["Dalc"]]).mean()

In [48]:
print("alc_mat", alc_mat)
print("alc_port", alc_port)

alc_mat 3.7721518987341773
alc_port 3.782742681047766


--> Die Studenten im Portugisisch-Kurs trinken etwas mehr

# Trinken Studierende mehr, wenn die Bildung der Mutter geringer ist? (Medu)

In [51]:
medu_col_index=col_index["Medu"]
np.unique(arr_mat[:,medu_col_index])

array([0, 1, 2, 3, 4], dtype=object)

Wir machen den Split bei Medu <3

nächster Schritt: walc und dalc -Mean() derjenigen mit medu <3 und >3 berechnen

In [56]:
low_edu_bool_index=arr_mat[:,medu_col_index] < 3
arr_mat[:,medu_col_index] < 3

array([False,  True,  True, False, False, False,  True, False, False,
       False, False,  True, False, False,  True, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False,  True,
       False, False, False,  True,  True, False, False,  True,  True,
       False, False, False, False, False,  True, False, False, False,
       False,  True, False, False,  True, False, False,  True,  True,
       False, False, False, False, False,  True, False, False, False,
        True, False, False, False, False,  True,  True, False,  True,
        True, False,  True,  True, False,  True, False,  True, False,
       False, False, False, False,  True,  True, False,  True, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False,  True, False,  True, False, False,
       False,  True, False,  True,  True,  True, False,  True, False,
       False,  True,

In [61]:
arr_mat[low_edu_bool_index,col_index["Walc"]].mean()

2.2848484848484847

In [62]:
foo_index=np.array([False, True])
foo_index

array([False,  True])

In [63]:
~foo_index

array([ True, False])

In [64]:
arr_mat[~low_edu_bool_index,col_index["Walc"]].mean()

2.2956521739130435

In [65]:
weekend_alc_high_edu=arr_mat[~low_edu_bool_index,col_index["Walc"]].mean()
weekend_alc_low_edu=arr_mat[low_edu_bool_index,col_index["Walc"]].mean()
workday_alc_high_edu=arr_mat[~low_edu_bool_index,col_index["Dalc"]].mean()
workday_alc_low_edu=arr_mat[low_edu_bool_index,col_index["Dalc"]].mean()

print("weekend_alc_high_edu", weekend_alc_high_edu)
print("weekend_alc_low_edu", weekend_alc_low_edu)
print("workday_alc_high_edu", workday_alc_high_edu)
print("workday_alc_low_edu", workday_alc_low_edu)

weekend_alc_high_edu 2.2956521739130435
weekend_alc_low_edu 2.2848484848484847
workday_alc_high_edu 1.5260869565217392
workday_alc_low_edu 1.4181818181818182


## Trinken Streber mehr? (studytime)

In [69]:
set(arr_mat[:,col_index["studytime"]])

{1, 2, 3, 4}

In [70]:
low_studytime_index=arr_mat[:,col_index["studytime"]]<3

low_studytime_alc=arr_mat[low_studytime_index,col_index["Dalc"]].mean()+arr_mat[low_studytime_index,col_index["Walc"]].mean()
high_studytime_alc=arr_mat[~low_studytime_index,col_index["Dalc"]].mean()+arr_mat[~low_studytime_index,col_index["Walc"]].mean()

print("low_studytime_alc", low_studytime_alc)
print("high_studytime_alc", high_studytime_alc)

low_studytime_alc 3.996699669966997
high_studytime_alc 3.032608695652174


# Trinken Studierende in einer Beziehung mehr?

In [73]:
np.unique(arr_mat[:, col_index["romantic"]])

array(['no', 'yes'], dtype=object)

In [75]:
no_romance_index=arr_mat[:,col_index["romantic"]]=='no'

no_romance_alc=arr_mat[no_romance_index,col_index["Dalc"]].mean()+arr_mat[no_romance_index,col_index["Walc"]].mean()
romance_alc=arr_mat[~no_romance_index,col_index["Dalc"]].mean()+arr_mat[~no_romance_index,col_index["Walc"]].mean()

print("no_romance_alc", no_romance_alc)
print("romance_alc", romance_alc)

no_romance_alc 3.7718631178707223
romance_alc 3.772727272727273


In [ ]:
low_high_edu_index=(arr_mat[:,medu_col_index]==2) | (arr_mat[:,medu_col_index]==4)