In [1]:
arr = [ 7, 9, 2, 1, 3, 9]

print(arr)

[7, 9, 2, 1, 3, 9]


In [2]:
for i in range(len(arr)):
    arr[i]=arr[i]+1

print(arr)

[8, 10, 3, 2, 4, 10]


In [6]:
arr_big=[1]*100000000

In [8]:
for i in range(len(arr_big)):
    arr_big[i]=arr_big[i]+1

In [9]:
import numpy as np

In [10]:
arr_big=np.array(arr_big)

In [11]:
arr_big

array([3, 3, 3, ..., 3, 3, 3])

In [12]:
for i in range(len(arr_big)):
    arr_big[i]=arr_big[i]+1

In [13]:
arr_big

array([4, 4, 4, ..., 4, 4, 4])

In [14]:
arr_big=arr_big+1

In [15]:
arr_big

array([5, 5, 5, ..., 5, 5, 5])

In [16]:
arr_2d=np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12 ]
])



In [17]:
# zeile 1 soll verdoppelt werden
arr_2d[1]=arr_2d[2]*2

arr_2d

array([[ 1,  2,  3,  4],
       [18, 20, 22, 24],
       [ 9, 10, 11, 12]])

# Selektieren von Bereichen

In [18]:
# spalte 2 selektieren

# : --> ALLE Zeilen werden genommen
# , --> Trennzeichen zwischen dem Zeilen- und Spaltenbereich
# 2 --> Spalte 2
arr_2d[:,2]

array([ 3, 22, 11])

In [22]:
# zeilen 1 und 2 mit der Spalte 3

arr_2d[1:3,3]

array([24, 12])

In [23]:
arr_2d[1:3,3]=arr_2d[1:3,3]*200

arr_2d

array([[   1,    2,    3,    4],
       [  18,   20,   22, 4800],
       [   9,   10,   11, 2400]])

# Boolean Index

In [25]:
col_index=[False, True, False, True]

arr_2d[1:2, col_index]

# Bereich vor dem Komma: Zeile 1 bis Zeile 2(exklusiv)
# Komma: trennt Zeilen und Spaltenbereich
# Nach dem Komma: col_index definiert genau, welche Spalten genommen werden dürfen (True)

array([[  20, 4800]])